name: WaffleEssentialsNK
main: com.indra87g.Main
version: "${pom.version}"
api: 1.0.0
author: indra87g
description: Lorem ipsum dolor sit amet.
commands:
permissions:
  waffle.setblock:
    description: "Allows the user to use the /setblock command"
    default: op
  waffle.servers:
    description: "Allows the user to use the /servers command"
    default: true
  waffle.info:
    description: "Allows the user to use the /info command"
    default: true
    children:
      waffle.info.player:
        description: "Allows the user to see and access the player info menu"
        default: op
      waffle.info.all:
        description: "Allows the user to see and access all menus in the info form"
        default: op
  waffle.redeem.admin:
    description: "Allows the user to manage redeem codes"
    default: op
