name: WaffleCoreNK
main: com.indra87g.Main
version: "${pom.version}"
api: 1.0.0
author: indra87g
description: Core plugin for the WaffleNK ecosystem.
commands:
  buyc:
    description: "Purchase commands using in-game currency"
    usage: "/buyc"
    permission: waffle.buyc
  near:
    description: "Shows nearby players"
    usage: "/near"
    permission: waffle.near
permissions:
  waffle.buyc:
    description: "Allows the user to use the /buyc command"
    default: true
  waffle.near:
    description: "Allows the user to use the /near command"
    default: op
  waffle.near.ignore:
    description: "Makes the player invisible to the /near command"
    default: op
  waffle.setblock:
    description: "Allows the user to use the /setblock command"
    default: op
  waffle.servers:
    description: "Allows the user to use the /servers command"
    default: true
  waffle.info:
    description: "Allows the user to use the /info command"
    default: true
    children:
      waffle.info.me:
        description: "Allows the user to use the /info me command"
        default: true
      waffle.info.server:
        description: "Allows the user to use the /info server command"
        default: true
      waffle.info.item:
        description: "Allows the user to use the /info item command"
        default: true
